import { StyleSheet } from 'react-native';

import type { Palette } from '@core/theme';
import { Fonts } from '@core/theme/fonts';
import { Radius } from '@core/theme/spacing';

// Estilos compartidos por la pantalla de inscripción y sus piezas (cabecera de
// pasos, bloque de jugador, selector de categoría).
export const makeSignupStyles = (c: Palette) =>
  StyleSheet.create({
    root: { flex: 1, backgroundColor: c.background },

    // ── Cabecera ───────────────────────────────────────────────────────
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingHorizontal: 18,
      paddingBottom: 12,
    },
    headerWrap: {
      borderBottomWidth: 1,
      borderColor: c.hair,
      backgroundColor: c.background,
    },
    backBtn: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: c.bgCard,
      borderWidth: 1,
      borderColor: c.hairStrong,
    },
    eyebrow: { fontFamily: Fonts.mono, fontSize: 11, letterSpacing: 3, color: c.accent, fontWeight: '500' },
    eyebrowStep: { fontFamily: Fonts.mono, fontSize: 10.5, letterSpacing: 1.6, color: c.accent, fontWeight: '600' },
    title: { color: c.text, fontSize: 20, fontWeight: '700', letterSpacing: -0.4, marginTop: 2 },
    progressRow: { flexDirection: 'row', gap: 6, paddingHorizontal: 18, paddingBottom: 12 },
    progressSeg: { flex: 1, height: 4, borderRadius: 2, backgroundColor: c.hairStrong },
    progressSegOn: { backgroundColor: c.accent },

    // ── Campos ─────────────────────────────────────────────────────────
    label: {
      fontFamily: Fonts.mono,
      fontSize: 11,
      letterSpacing: 2,
      color: c.textFaint,
      textTransform: 'uppercase',
      fontWeight: '500',
      marginTop: 16,
      marginBottom: 8,
    },
    input: {
      backgroundColor: c.bgCard,
      borderRadius: Radius.md,
      borderWidth: 1,
      borderColor: c.hairStrong,
      paddingHorizontal: 14,
      minHeight: 50,
      justifyContent: 'center',
    },
    inputError: { borderColor: c.error },
    inputField: { color: c.text, fontSize: 15, fontWeight: '500', paddingVertical: 0 },
    fieldError: { color: c.error, fontSize: 12.5, fontWeight: '600', marginTop: 6, lineHeight: 17 },
    fieldHint: { color: c.textMuted, fontSize: 12, marginTop: 6, lineHeight: 17 },
    two: { flexDirection: 'row', gap: 12 },
    linkText: { color: c.accent, fontSize: 13, fontWeight: '700' },
    linkRow: { marginTop: 10, alignSelf: 'flex-start' },

    // ── Búsqueda y ficha del torneo ────────────────────────────────────
    lookupBtn: {
      paddingHorizontal: 18,
      minHeight: 50,
      borderRadius: Radius.md,
      backgroundColor: c.accent10,
      borderWidth: 1,
      borderColor: c.accent40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    lookupText: { color: c.accent, fontSize: 14, fontWeight: '700' },
    foundCard: {
      marginTop: 12,
      padding: 14,
      borderRadius: Radius.md,
      backgroundColor: c.bgCard,
      borderWidth: 1,
      borderColor: c.accent25,
    },
    foundName: { color: c.text, fontSize: 17, fontWeight: '800', letterSpacing: -0.3 },
    infoBox: { marginTop: 12, borderTopWidth: 1, borderColor: c.hair },
    infoRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
      paddingVertical: 9,
      borderBottomWidth: 1,
      borderColor: c.hair,
    },
    infoRowLast: { borderBottomWidth: 0 },
    infoLabel: {
      fontFamily: Fonts.mono,
      fontSize: 10.5,
      letterSpacing: 1,
      color: c.textFaint,
      fontWeight: '700',
      width: 92,
      paddingTop: 1,
    },
    infoValue: { flex: 1, minWidth: 0, color: c.text, fontSize: 13.5, fontWeight: '600', lineHeight: 19 },
    webNote: { color: c.textMuted, fontSize: 13.5, lineHeight: 20, marginTop: 4 },

    // ── Chips (género) ─────────────────────────────────────────────────
    catChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    catChip: {
      paddingHorizontal: 16,
      height: 42,
      borderRadius: Radius.md,
      backgroundColor: c.bgRaised,
      borderWidth: 1,
      borderColor: c.hairStrong,
      alignItems: 'center',
      justifyContent: 'center',
    },
    catChipText: { fontSize: 15, fontWeight: '700' },

    // ── Bloque de jugador ──────────────────────────────────────────────
    block: {
      marginTop: 18,
      padding: 14,
      paddingTop: 2,
      borderRadius: Radius.lg,
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.hair,
    },
    blockTitle: {
      fontFamily: Fonts.mono,
      fontSize: 11,
      letterSpacing: 2.4,
      color: c.accent,
      fontWeight: '700',
      marginTop: 12,
    },
    blockNote: { color: c.textMuted, fontSize: 12, marginTop: 4, lineHeight: 17 },
    noFedRow: {
      marginTop: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: Radius.md,
      backgroundColor: c.bgCard,
      borderWidth: 1,
      borderColor: c.hairStrong,
    },
    noFedText: { flex: 1, color: c.textMuted, fontSize: 13, fontWeight: '600' },

    // Sugerencia de la Federación
    suggestWrap: {
      marginTop: 10,
      backgroundColor: c.accent10,
      borderWidth: 1,
      borderColor: c.accent40,
      borderRadius: Radius.md,
      paddingHorizontal: 14,
      paddingVertical: 12,
      gap: 8,
    },
    suggestLabel: {
      fontFamily: Fonts.mono,
      fontSize: 10,
      letterSpacing: 1.4,
      color: c.accent,
      fontWeight: '700',
    },
    suggestRow: { gap: 8 },
    suggestChip: {
      backgroundColor: c.bgCard,
      borderWidth: 1,
      borderColor: c.hairStrong,
      borderRadius: Radius.md,
      paddingHorizontal: 14,
      paddingVertical: 12,
    },
    suggestName: { color: c.text, fontSize: 14.5, fontWeight: '700' },
    suggestMeta: { fontFamily: Fonts.mono, color: c.textMuted, fontSize: 11.5, marginTop: 4 },
    suggestHint: { color: c.textFaint, fontSize: 11 },
    confirmRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    confirmTick: { color: c.accent, fontSize: 16, fontWeight: '900' },

    // ── Selector de categoría ──────────────────────────────────────────
    stepSub: { color: c.textMuted, fontSize: 13.5, fontWeight: '600', marginTop: 14, lineHeight: 19 },
    catList: { gap: 8, marginTop: 6 },
    catCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingHorizontal: 14,
      paddingVertical: 13,
      borderRadius: Radius.md,
      backgroundColor: c.bgCard,
      borderWidth: 1,
      borderColor: c.hairStrong,
    },
    catCardSel: { borderColor: c.accent, backgroundColor: c.accent10 },
    catCardOff: { opacity: 0.45 },
    radio: {
      width: 20,
      height: 20,
      borderRadius: 10,
      borderWidth: 1.5,
      borderColor: c.hairStrong,
      alignItems: 'center',
      justifyContent: 'center',
    },
    radioOn: { borderColor: c.accent },
    radioDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: c.accent },
    catName: { color: c.text, fontSize: 15.5, fontWeight: '800' },
    catDetail: { fontFamily: Fonts.mono, color: c.textMuted, fontSize: 11.5, marginTop: 3 },
    catReason: { color: c.textMuted, fontSize: 12, marginTop: 3, lineHeight: 16 },
    emptyBox: {
      marginTop: 14,
      padding: 16,
      borderRadius: Radius.lg,
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.hair,
      gap: 10,
    },
    emptyTitle: { color: c.text, fontSize: 15, fontWeight: '800' },
    emptyText: { color: c.textMuted, fontSize: 13, lineHeight: 19 },
    ghostBtn: {
      alignSelf: 'flex-start',
      paddingHorizontal: 14,
      height: 40,
      borderRadius: Radius.md,
      backgroundColor: c.accent10,
      borderWidth: 1,
      borderColor: c.accent40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    ghostBtnText: { color: c.accent, fontSize: 13.5, fontWeight: '700' },
    addSecondBtn: {
      marginTop: 18,
      paddingVertical: 14,
      borderRadius: Radius.md,
      borderWidth: 1,
      borderStyle: 'dashed',
      borderColor: c.accent40,
      alignItems: 'center',
    },
    secondCatBlock: {
      marginTop: 18,
      padding: 14,
      paddingTop: 2,
      borderRadius: Radius.lg,
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.accent25,
    },
    secondHead: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 12,
    },

    // ── Paso 3: horario, condiciones, resumen ──────────────────────────
    availHead: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 16,
      marginBottom: 8,
    },
    capChip: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 9999,
      backgroundColor: c.accent10,
      borderWidth: 1,
      borderColor: c.accent40,
    },
    capChipText: { fontFamily: Fonts.mono, color: c.accent, fontSize: 11.5, fontWeight: '700' },
    availHint: { color: c.textMuted, fontSize: 12, marginBottom: 10, lineHeight: 17 },
    franjaBlock: { marginBottom: 12 },
    franjaLabel: {
      fontFamily: Fonts.mono,
      fontSize: 13,
      fontWeight: '700',
      color: c.text,
      marginBottom: 6,
    },
    hourGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
    hourCell: {
      width: 86,
      height: 38,
      borderRadius: Radius.sm,
      backgroundColor: c.bgCard,
      borderWidth: 1,
      borderColor: c.hairStrong,
      alignItems: 'center',
      justifyContent: 'center',
    },
    hourCellText: { fontFamily: Fonts.mono, fontSize: 11.5, fontWeight: '700' },
    termsRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 18 },
    termsAccept: { color: c.text, fontSize: 13.5, fontWeight: '700', flex: 1 },
    termsText: {
      marginTop: 10,
      padding: 12,
      borderRadius: Radius.md,
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.hair,
      color: c.textMuted,
      fontSize: 12.5,
      lineHeight: 19,
    },
    checkBox: {
      width: 20,
      height: 20,
      borderRadius: 6,
      borderWidth: 1.5,
      borderColor: c.hairStrong,
      alignItems: 'center',
      justifyContent: 'center',
    },
    checkBoxOn: { backgroundColor: c.accent, borderColor: c.accent },
    checkMark: { color: c.textInverse, fontSize: 12, fontWeight: '900' },
    summary: {
      marginTop: 18,
      paddingHorizontal: 14,
      paddingVertical: 4,
      borderRadius: Radius.lg,
      backgroundColor: c.bgCard,
      borderWidth: 1,
      borderColor: c.accent25,
    },

    // ── Pie con botones ────────────────────────────────────────────────
    footer: {
      paddingHorizontal: 22,
      paddingTop: 10,
      borderTopWidth: 1,
      borderColor: c.hair,
      backgroundColor: c.background,
    },
    footerRow: { flexDirection: 'row', gap: 10 },
    saveBtn: {
      flex: 1,
      height: 52,
      borderRadius: Radius.lg,
      backgroundColor: c.accent,
      alignItems: 'center',
      justifyContent: 'center',
    },
    saveLabel: { color: c.textInverse, fontSize: 15, fontWeight: '700', letterSpacing: -0.2 },
    stepBackBtn: {
      height: 52,
      paddingHorizontal: 18,
      borderRadius: Radius.lg,
      backgroundColor: c.bgCard,
      borderWidth: 1,
      borderColor: c.hairStrong,
      alignItems: 'center',
      justifyContent: 'center',
    },
    stepBackText: { color: c.text, fontSize: 15, fontWeight: '700' },

    // ── Éxito: tarjeta tipo entrada ────────────────────────────────────
    successTitle: {
      color: c.text,
      fontSize: 28,
      fontWeight: '800',
      textAlign: 'center',
      letterSpacing: -0.6,
    },
    successText: {
      color: c.textMuted,
      fontSize: 14.5,
      lineHeight: 21,
      textAlign: 'center',
      marginTop: 10,
    },
    ticket: {
      marginTop: 20,
      backgroundColor: c.bgCard,
      borderWidth: 1,
      borderColor: c.accent40,
      borderRadius: 18,
      overflow: 'hidden',
    },
    ticketTop: { paddingHorizontal: 18, paddingTop: 16, paddingBottom: 6 },
    ticketEyebrow: { fontFamily: Fonts.mono, color: c.accent, fontSize: 10.5, letterSpacing: 2, fontWeight: '700' },
    ticketName: { color: c.text, fontSize: 19, fontWeight: '800', letterSpacing: -0.4, marginTop: 6 },
    ticketCut: {
      flexDirection: 'row',
      alignItems: 'center',
      marginVertical: 8,
    },
    ticketNotch: {
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: c.background,
      borderWidth: 1,
      borderColor: c.accent40,
    },
    ticketDash: {
      flex: 1,
      borderTopWidth: 1.5,
      borderStyle: 'dashed',
      borderColor: c.hairStrong,
      marginHorizontal: 6,
    },
    ticketBottom: { alignItems: 'center', paddingHorizontal: 18, paddingBottom: 20 },
    codeBigLabel: {
      fontFamily: Fonts.mono,
      color: c.textFaint,
      fontSize: 11,
      letterSpacing: 2,
    },
    codeBig: {
      fontFamily: Fonts.mono,
      color: c.accent,
      fontSize: 40,
      fontWeight: '800',
      letterSpacing: 8,
      marginTop: 8,
    },
    ticketNote: { color: c.textMuted, fontSize: 13, lineHeight: 19, textAlign: 'center', marginTop: 6 },
    primaryBtn: {
      marginTop: 22,
      backgroundColor: c.accent,
      borderRadius: 14,
      paddingVertical: 15,
      alignItems: 'center',
    },
    primaryBtnText: { color: c.textInverse, fontSize: 15.5, fontWeight: '800' },
    secondaryBtn: { marginTop: 10, paddingVertical: 14, alignItems: 'center' },
    secondaryBtnText: { color: c.textMuted, fontSize: 15, fontWeight: '700' },
  });

export type SignupStyles = ReturnType<typeof makeSignupStyles>;
